"""add one more column to Logs

Revision ID: 205de0463599
Revises: ac2548a82dc6
Create Date: 2021-06-26 18:16:50.846303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205de0463599'
down_revision = 'ac2548a82dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'valid')
    # ### end Alembic commands ###
